# Generated by Django 6.0.3 on 2026-03-05 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(max_length=255)),
                ('company', models.CharField(max_length=255)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, help_text='Leave blank if this is your current role', null=True)),
                ('is_current', models.BooleanField(default=False)),
                ('description', models.TextField()),
                ('highlights', models.JSONField(default=list, help_text='List of key achievements/skills')),
                ('is_published', models.BooleanField(default=True)),
                ('created_when', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Experiences',
                'ordering': ['-start_date'],
            },
        ),
    ]
