# Generated by Django 6.0.3 on 2026-03-05 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField(blank=True, max_length=255, unique=True)),
                ('category', models.CharField(choices=[('design', 'Design (UI/UX, Figma)'), ('frontend', 'Frontend'), ('backend', 'Backend'), ('fullstack', 'Fullstack')], default='fullstack', max_length=20)),
                ('description', models.TextField()),
                ('my_contributions', models.TextField(help_text='Detail your specific roles and achievements here.')),
                ('image', models.ImageField(blank=True, null=True, upload_to='project_images/')),
                ('tags', models.JSONField(default=list, help_text='List of technologies used')),
                ('code_link', models.URLField(blank=True, null=True)),
                ('demo_link', models.URLField(blank=True, null=True)),
                ('is_published', models.BooleanField(default=True)),
                ('created_when', models.DateTimeField(auto_now_add=True)),
                ('order', models.PositiveIntegerField(default=0, help_text='Lower numbers appear first')),
            ],
            options={
                'ordering': ['order', '-created_when'],
            },
        ),
    ]
