# Generated by Django 6.0.3 on 2026-03-05 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Certification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('issuer', models.CharField(help_text='e.g., Coursera, AWS, HackerRank', max_length=255)),
                ('type', models.CharField(choices=[('certification', 'Certification'), ('award', 'Award / Honor')], default='certification', max_length=20)),
                ('date_issued', models.DateField()),
                ('credential_url', models.URLField(blank=True, help_text='Link to verify the certificate', null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='certifications/')),
                ('description', models.TextField(blank=True, help_text='Brief details about what the certification covers')),
                ('is_published', models.BooleanField(default=True)),
                ('order', models.PositiveIntegerField(default=0, help_text='Lower numbers appear first')),
            ],
            options={
                'ordering': ['order', '-date_issued'],
            },
        ),
    ]
